import Head from 'next/head';
import React from 'react';
import Footer from './Footer';
import Navbar from './Navbar';

function Layout({ children }: { children: any }) {
  return (
    <div className='min-h-screen grid grid-rows-[auto_1fr_auto]'>
      <Head>
        <title>hackerNation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}

export default Layout;
